### ISSUE TITLE
Collaboration for computer vision project

### ISSUE THREAD

**Issue by rozeappletree** [amitbcp/computer-vision-nanodegree#6]
Hi,

I did not know how to reach you so opening issue here. Please close if it seems irrelevant.

I saw your GitHub status *"Looking to collaborate on Computer Vision projects"*. If you're still open to talk about it, please do let me know.

We have around 6k HD ANNOTATED (segmentation masks) panaromic view images. We are failing to get better accuracy using detectron2 framework (mask rcnn).  I think your insights will be really helpful in this matter.

Thanks and regards,
Rakesh

**Comment by rozeappletree** [comment]
@amitbcp

**Comment by amitbcp** [comment]
@INF800 thanks for reaching out. But at the present moment,  I am in middle of other commitments which requires to be completed. Hopefully in the future we can collaborate.
